README.md
doc/source/conf.py
doc/source/getting_started/Citations.md
doc/source/user_guide/time.rst
doc/source/user_guide/utilities.rst
environment.yml
pyTMD/time.py
pyTMD/utilities.py
requirements.txt
scripts/compute_tidal_elevations.py
scripts/compute_tides_ICESat2_ATL03.py
scripts/compute_tides_ICESat2_ATL06.py
scripts/compute_tides_ICESat2_ATL07.py
scripts/compute_tides_ICESat2_ATL12.py
scripts/compute_tides_icebridge_data.py
setup.py

add NASA Earthdata login for Bulletin-A and delta time files from [NASA GSFC CDDIS](https://cddis.nasa.gov/)
add lxml requirement and update documentation

update asserted model list in OIB and ICESat-2 programs

---

.github/workflows/python-package.yml
.github/workflows/python-request.yml

will install dependencies with homebrew package manager

add macos-latest to testing strategy

---

.github/workflows/python-package.yml
.github/workflows/python-request.yml
README.md
codecov.yml
doc/source/conf.py
doc/source/getting_started/Install.md
doc/source/user_guide/convert_ll_xy.md
pyTMD/compute_tide_corrections.py
pyTMD/convert_ll_xy.py
pytest.ini
setup.cfg
setup.py
test/test_coordinates.py
test/test_download_and_read.py
test/test_equilibrium_tides.py

update coordinate conversions for pyproj2
add coordinate conversion test
reorganize badges for consistency
create setup.cfg for both pytest and coverage
archive coverage.yml for job as artifact

add code coverage check and badge

---

doc/source/conf.py
pyTMD/calc_astrol_longitudes.py
pyTMD/compute_tide_corrections.py
pyTMD/convert_calendar_decimal.py
pyTMD/convert_julian.py
pyTMD/infer_minor_corrections.py
pyTMD/load_nodal_corrections.py
pyTMD/read_FES_model.py
pyTMD/read_GOT_model.py
pyTMD/read_netcdf_model.py
pyTMD/read_tide_model.py
pyTMD/time.py
pyTMD/utilities.py
setup.py
test/test_download_and_read.py
test/test_leap_seconds.py
test/test_time.py

verifies outputs to address #6 
use numpy atleast_1d for time values
use netrc within utilities for backup authentication

test OTIS current predictions

---

doc/source/getting_started/Getting-Started.md
doc/source/index.rst
doc/source/user_guide/compute_LPET_ICESat_GLA12.md
doc/source/user_guide/compute_LPET_elevations.md
doc/source/user_guide/compute_LPET_icebridge_data.md
doc/source/user_guide/compute_LPT_ICESat_GLA12.md
doc/source/user_guide/compute_LPT_icebridge_data.md
doc/source/user_guide/compute_OPT_ICESat_GLA12.md
doc/source/user_guide/compute_OPT_displacements.md
doc/source/user_guide/compute_tides_ICESat_GLA12.md
doc/source/user_guide/spatial.rst
doc/source/user_guide/utilities.rst
pyTMD/load_nodal_corrections.py
pyTMD/spatial.py
pyTMD/utilities.py
scripts/compute_LPET_ICESat2_ATL03.py
scripts/compute_LPET_ICESat_GLA12.py
scripts/compute_LPT_ICESat_GLA12.py
scripts/compute_LPT_displacements.py
scripts/compute_LPT_icebridge_data.py
scripts/compute_OPT_ICESat_GLA12.py
scripts/compute_OPT_displacements.py
scripts/compute_OPT_icebridge_data.py
scripts/compute_tides_ICESat2_ATL03.py
scripts/compute_tides_ICESat_GLA12.py
test/test_spatial.py

updated spatial module to add convert ellipsoids for TPX to WGS84
add equilibrium, load, ocean load pole tide programs for GLA12
update documentation for ICESat programs
add convert ellipsoid test program
Thanks Bastiaan Les for pointing out FES k1 problems

added module for computing tides for ICESat GLA12

---

.github/workflows/auto-update-files.yml
doc/source/user_guide/spatial.rst
doc/source/user_guide/utilities.rst
pyTMD/spatial.py
pyTMD/time.py
pyTMD/utilities.py
test/test_atlas_read.py
test/test_download_and_read.py
test/test_perth3_read.py
test/test_spatial.py
test/test_utilities.py

add ftp connection check
update tests to use wrapper function for OTIS

add streaming from bytes for ascii, netCDF4, HDF5, geotiff

---

doc/source/getting_started/Getting-Started.rst
pyTMD/spatial.py
pyTMD/time.py
test/test_time.py

set default time to zero for geotiff

add date parser for cases when only a calendar date with no units

---

doc/source/user_guide/compute_LPET_ICESat2_ATL11.md
doc/source/user_guide/compute_tides_ICESat2_ATL11.md
pyTMD/bilinear_interp.py
pyTMD/compute_tide_corrections.py
pyTMD/iers_mean_pole.py
pyTMD/nearest_extrap.py
pyTMD/predict_tidal_ts.py
pyTMD/predict_tide.py
pyTMD/predict_tide_drift.py
pyTMD/read_FES_model.py
pyTMD/read_GOT_model.py
pyTMD/read_netcdf_model.py
pyTMD/read_tide_model.py
scripts/compute_LPET_ICESat2_ATL11.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
scripts/compute_tides_ICESat2_ATL11.py
test/test_download_and_read.py
test/test_fes_predict.py
test/test_perth3_read.py

replaced numpy bool to prevent deprecation warning

calculate tides for ATL11 crossing track data

---

doc/source/user_guide/spatial.rst
pyTMD/nearest_extrap.py
pyTMD/read_FES_model.py
pyTMD/read_GOT_model.py
pyTMD/read_netcdf_model.py
pyTMD/read_tide_model.py
pyTMD/spatial.py
scripts/compute_LPT_ICESat_GLA12.py
scripts/compute_LPT_displacements.py
scripts/compute_LPT_icebridge_data.py
scripts/compute_OPT_ICESat_GLA12.py
scripts/compute_OPT_displacements.py
scripts/compute_OPT_icebridge_data.py
test/test_interpolate.py

add routines for converting to and from cartesian coordinates
use cartesian coordinate conversion routine for LPT and OPT
add tests for interpolation, extrapolation and extrapolation checks

add checks for extrapolate points to avoid exceptions

---

doc/source/user_guide/compute_tide_corrections.md
doc/source/user_guide/spatial.rst
doc/source/user_guide/time.rst
pyTMD/check_tide_points.py
pyTMD/compute_tide_corrections.py
pyTMD/read_FES_model.py
pyTMD/read_GOT_model.py
pyTMD/read_iers_EOP.py
pyTMD/read_netcdf_model.py
pyTMD/read_ocean_pole_tide.py
pyTMD/read_tide_model.py
pyTMD/spatial.py
pyTMD/time.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
scripts/reduce_OTIS_files.py
test/test_perth3_read.py
test/test_spatial.py

feat: added function for determining the input spatial variable type
feat: added function for converting numpy datetimes to relative
feat: added checks that tide model directories and files are accessible
test: check that type function is working
test: test that access checks are working
fix: variable name in reduce OTIS program

feat: can use numpy datetime arrays as input time variable

---

doc/source/user_guide/usap_cats_tides.md
doc/source/user_guide/utilities.rst
pyTMD/spatial.py
pyTMD/utilities.py
scripts/usap_cats_tides.py
test/test_download_and_read.py
test/test_spatial.py

test: download CATS2008 from s3 bucket

fix: USAP now requires capchas

---

doc/source/getting_started/Contributing.rst
doc/source/user_guide/spatial.rst
pyTMD/read_netcdf_model.py
pyTMD/spatial.py
test/test_download_and_read.py

feat: calculator for height differences between ellipsoids

fix: netCDF4 cases with no mask on constituent files to address #66

---

doc/source/getting_started/Getting-Started.rst
doc/source/user_guide/compute_tidal_currents.md
doc/source/user_guide/compute_tidal_elevations.md
doc/source/user_guide/compute_tides_ICESat2_ATL03.md
doc/source/user_guide/compute_tides_ICESat2_ATL06.md
doc/source/user_guide/compute_tides_ICESat2_ATL07.md
doc/source/user_guide/compute_tides_ICESat2_ATL11.md
doc/source/user_guide/compute_tides_ICESat2_ATL12.md
doc/source/user_guide/compute_tides_ICESat_GLA12.md
doc/source/user_guide/compute_tides_icebridge_data.md
doc/source/user_guide/verify_box_tpxo.md
notebooks/Check Tide Map.ipynb
notebooks/Plot Antarctic Tidal Currents.ipynb
notebooks/Plot Antarctic Tide Range.ipynb
notebooks/Plot Arctic Ocean Map.ipynb
notebooks/Plot Ross Ice Shelf Map.ipynb
notebooks/Plot Tide Forecasts.ipynb
pyTMD/model.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
scripts/compute_tides_ICESat2_ATL03.py
scripts/compute_tides_ICESat2_ATL06.py
scripts/compute_tides_ICESat2_ATL07.py
scripts/compute_tides_ICESat2_ATL11.py
scripts/compute_tides_ICESat2_ATL12.py
scripts/compute_tides_ICESat_GLA12.py
scripts/compute_tides_icebridge_data.py
scripts/verify_box_tpxo.py

docs: add TPXO9-atlas-v5 to overview

feat: add TPXO9-atlas-v5 to standard models

---

doc/source/getting_started/Getting-Started.rst
doc/source/user_guide/compute_LPET_elevations.md
doc/source/user_guide/compute_LPT_displacements.md
doc/source/user_guide/compute_OPT_displacements.md
doc/source/user_guide/compute_tidal_currents.md
doc/source/user_guide/compute_tidal_elevations.md
doc/source/user_guide/compute_tide_corrections.md
pyTMD/compute_tide_corrections.py
pyTMD/spatial.py
scripts/compute_LPET_elevations.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
test/test_equilibrium_tides.py

fix: remove fill_value attribute after creating netCDF4 and HDF5 variables

feat: option for changing time standard in file programs

---

doc/source/user_guide/nearest_extrap.md
pyTMD/nearest_extrap.py

feat: parameters for inverse distance weighted (IDW) extrapolation

fix: extrapolate for equirectangular case to address #87

---

.github/workflows/python-request.yml
doc/environment.yml
doc/source/user_guide/spatial.rst
environment.yml
pyTMD/eop.py
pyTMD/model.py
pyTMD/nearest_extrap.py
pyTMD/output_otis_tides.py
pyTMD/read_FES_model.py
pyTMD/read_GOT_model.py
pyTMD/read_iers_EOP.py
pyTMD/read_netcdf_model.py
pyTMD/read_ocean_pole_tide.py
pyTMD/read_tide_model.py
pyTMD/spatial.py
pyTMD/time.py
scripts/compute_LPET_icebridge_data.py
scripts/compute_LPT_icebridge_data.py
scripts/compute_OPT_ICESat_GLA12.py
scripts/compute_OPT_displacements.py
scripts/compute_OPT_icebridge_data.py
scripts/compute_tides_icebridge_data.py
setup.py
test/test_ocean_pole_tide.py
test/test_spatial.py

fix: fes masks to address #96
refactor: h5py in try/except for slimmer build to address #94
refactor: windows compliant reads

fix: use valid points in extrapolation to address #87

---

doc/source/api_reference/compute_LPET_elevations.rst
doc/source/api_reference/compute_LPT_displacements.rst
doc/source/api_reference/compute_OPT_displacements.rst
doc/source/api_reference/compute_tidal_currents.rst
doc/source/api_reference/compute_tidal_elevations.rst
pyTMD/spatial.py
test/test_spatial.py

fix: include more possible dimension names for gridded and drift outputs

test: validate gridded and time series netCDF/HDF5 io

---

doc/source/api_reference/compute_tide_corrections.rst
pyTMD/__init__.py
pyTMD/compute_tide_corrections.py
pyTMD/constants.py
pyTMD/eop.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
test/test_eop.py

feat: added option to change IERS mean or secular pole convention
feat: added 2018 IERS secular pole convention
feat: set ellipsoid name and output units as constants attributes

feat: added "one-liners" for LPET, LPT and OPT

---

notebooks/Plot ATLAS Compact.ipynb
notebooks/Plot Antarctic Tidal Currents.ipynb
notebooks/Plot Antarctic Tide Range.ipynb
notebooks/Plot Arctic Ocean Map.ipynb
notebooks/Plot Ross Ice Shelf Map.ipynb
pyTMD/io/model.py

refactor: mapping notebooks for matplotlib 3.5

---

doc/source/getting_started/Background.rst
doc/source/getting_started/Getting-Started.rst
doc/source/index.rst
pyTMD/io/model.py
pyTMD/predict.py
test/test_solid_earth.py

refactor: make mass ratios of sun/moon kwargs
refactor: output solid earth corrections as XYZ
docs: add background section detailing methods

refactor: make nominal love/shida numbers kwargs

---

CODE_OF_CONDUCT.rst
README.rst
doc/source/getting_started/Citations.rst
doc/source/getting_started/Contributing.rst
pyTMD/astro.py
pyTMD/convert_crs.py
pyTMD/eop.py
pyTMD/io/model.py
pyTMD/spatial.py
test/test_solid_earth.py
test/test_spatial.py

feat: allow netCDF4 and HDF5 outputs to be appended to existing files
feat: add code of conduct

fix: solar ephemeride function to include SSB-to-sun segment

---

doc/source/getting_started/Getting-Started.rst
doc/source/getting_started/Overview.rst
pyTMD/check_tide_points.py
pyTMD/compute_tide_corrections.py
pyTMD/convert_crs.py
pyTMD/io/ATLAS.py
pyTMD/io/FES.py
pyTMD/io/GOT.py
pyTMD/io/OTIS.py
pyTMD/spatial.py
pyTMD/time.py
scripts/compute_LPET_elevations.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
scripts/compute_SET_displacements.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
scripts/reduce_OTIS_files.py

docs: update graphviz fonts
refactor: switch from import `warnings` to debug `logging`

feat: improve conversion of timescale to datetime arrays

---

.github/workflows/auto-update-bulletin-a.yml
.github/workflows/auto-update-files.yml
.github/workflows/python-request.yml
doc/source/getting_started/Getting-Started.rst
notebooks/Check Tide Map.ipynb
notebooks/Plot Antarctic Tidal Currents.ipynb
notebooks/Plot Antarctic Tide Range.ipynb
notebooks/Plot Arctic Ocean Map.ipynb
notebooks/Plot Ross Ice Shelf Map.ipynb
notebooks/Plot Tide Forecasts.ipynb
pyTMD/arguments.py
pyTMD/check_tide_points.py
pyTMD/compute_tide_corrections.py
pyTMD/io/OTIS.py
pyTMD/io/constituents.py
pyTMD/io/model.py
pyTMD/predict.py
pyTMD/spatial.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py

refactor: changed ESR netCDF4 format to TMD3 format
fix: remove possible crs variables from output netCDF4 fields list

feat: added model parameters for CATS2023!

---

.github/workflows/auto-update-bulletin-a.yml
.github/workflows/auto-update-files.yml
.github/workflows/python-publish.yml
.github/workflows/python-request.yml
doc/source/api_reference/spatial.rst
doc/source/release_notes/release-v2.0.7.rst
pyTMD/astro.py
pyTMD/check_tide_points.py
pyTMD/compute_tide_corrections.py
pyTMD/convert_crs.py
pyTMD/io/ATLAS.py
pyTMD/io/FES.py
pyTMD/io/GOT.py
pyTMD/io/OTIS.py
pyTMD/spatial.py
pyTMD/tools.py
readthedocs.yml
scripts/compute_LPET_elevations.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
scripts/compute_SET_displacements.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
scripts/reduce_OTIS_files.py

docs: use micromamba for builds

ci: bump versions of imports to prevent deprecation errors

---

doc/source/api_reference/io/ATLAS.rst
doc/source/api_reference/io/FES.rst
doc/source/api_reference/io/GOT.rst
doc/source/api_reference/io/OTIS.rst
pyTMD/io/ATLAS.py
pyTMD/io/FES.py
pyTMD/io/GOT.py
pyTMD/io/OTIS.py
pyTMD/io/ocean_pole_tide.py
test/test_atlas_read.py
test/test_download_and_read.py
test/test_fes_predict.py
test/test_perth3_read.py

refactor: renamed OTIS currents masks and bathymetry interpolation functions
refactor: renamed extend array and matrix functions

fix: construct OTIS currents masks differently if not global

---

README.rst
doc/source/api_reference/astro.rst
doc/source/api_reference/spatial.rst
doc/source/getting_started/Citations.rst
doc/source/getting_started/Resources.rst
pyTMD/__init__.py
pyTMD/astro.py
pyTMD/compute.py
pyTMD/io/__init__.py
pyTMD/predict.py
pyTMD/solve/__init__.py
pyTMD/spatial.py
pyTMD/utilities.py
scripts/compute_LPET_elevations.py
scripts/compute_LPT_displacements.py
scripts/compute_SET_displacements.py
scripts/compute_tidal_currents.py
scripts/compute_tidal_elevations.py
test/test_arguments.py
test/test_solid_earth.py
test/test_spatial.py

feat: add wrapper function for normalizing phase angles
feat: add functions to convert to and from Degree-Minutes-Seconds (DMS)
fix: assert that data type is a known value

docs: add references to new PERTH5 software from Richard Ray

---

doc/source/api_reference/spatial.rst
pyTMD/compute.py
pyTMD/spatial.py
scripts/compute_LPT_displacements.py
scripts/compute_OPT_displacements.py
scripts/compute_SET_displacements.py
test/test_pole_tide.py
test/test_spatial.py

refactor: use rotation matrix to convert from cartesian to spherical

feat: add ECEF to ENU conversions

---

.github/workflows/update-provider-database.yml
providers/GSFC.json
pyTMD/data/database.json
pyTMD/io/model.py

refactor: drop `to_bool` function from `model` class

ci: try adding provider update

---

doc/source/_assets/pytmd-refs.bib
doc/source/background/Reference-Systems.rst
doc/source/background/Tides.rst
doc/source/background/love-numbers.py
doc/source/background/spectra.py
pyTMD/arguments.py
pyTMD/spatial.py
test/test_love_numbers.py

feat: add more ellipsoidal parameters to datum class
docs: add section for Celestial Reference Systems
test: add Love number ratio check
docs: add reference to J. Wahr 1979 PhD thesis
docs: add Love numbers plot from Wahr 1979

feat: add 1066A-N and 1066A-S Earth models to Love number calculation

---

doc/source/_assets/constituents.csv
doc/source/api_reference/astro.rst
doc/source/background/Astronomy.rst
doc/source/background/Tides.rst
doc/source/notebooks/Compare-Tide-Gauges.ipynb
pyTMD/arguments.py
pyTMD/astro.py
pyTMD/compute.py
pyTMD/crs.py
pyTMD/interpolate.py
pyTMD/io/OTIS.py
pyTMD/io/model.py

feat: added function to calculate equation of time
docs: add inverse of arguments
docs: update constituent table
docs: include LSSD to tide gauge comparison
docs: update dictionary keys

feat: use string mapping to remap non-numeric Doodson numbers

---

doc/source/api_reference/astro.rst
pyTMD/arguments.py
pyTMD/astro.py
test/test_arguments.py
test/test_astro.py
test/test_solid_earth.py

refactor: convert longitudes p and n to radians within nodal function
test: moved astro tests into new module

feat: use schureman arguments function for FES nodal variables

---

.gitignore
pyTMD/io/model.py
pyTMD/solve/constants.py
test/test_model.py

fix: verify all height and time variables are finite

fix: pass **kwargs to load_database

---

.github/workflows/python-request.yml
.github/workflows/update-provider-database.yml
doc/source/api_reference/ellipse.rst
doc/source/background/Tides.rst
doc/source/getting_started/Getting-Started.rst
doc/source/notebooks/Plot-Tide-Forecasts.ipynb
doc/source/release_notes/release-v2.1.1.rst
doc/source/release_notes/release-v2.2.2.rst
pyTMD/compute.py
pyTMD/compute_tide_corrections.py
pyTMD/ellipse.py
test/test_math.py

ci: add paths for running workflows

feat: add function to get the x/y of a tidal ellipse

---

.github/workflows/python-request.yml
.github/workflows/update-provider-database.yml
pyTMD/predict.py
scripts/aviso_fes_tides.py
test/test_solid_earth.py

fix: revert free-to-mean conversion to 2023 version

feat: added extrapolation option for FES2014 download

---

doc/source/conf.py
doc/source/constituent_table.py
doc/source/getting_started/Getting-Started.rst
doc/source/model_table.py

docs: include constituent table code for #425

docs: autogenerate model table

---

doc/source/notebooks/Plot-Ocean-Pole-Tide-Map.ipynb
pyTMD/predict.py
test/test_pole_tide.py

https://ilrs.gsfc.nasa.gov/docs/1996/iers_1996_conventions.pdf

fix: revert load pole tide to IERS 1996 convention definitions

---

doc/source/api_reference/arguments.rst
doc/source/notebooks/Compare-NOAA-Tides.ipynb
pyTMD/arguments.py
pyTMD/io/NOAA.py
pyTMD/predict.py
test/test_love_numbers.py
test/test_solid_earth.py

- feat: add anelastic correction for long-period body tides
- test: add check for long-period complex love numbers

fix: replace invalid NOAA water level values

---

.github/workflows/python-request.yml
doc/source/api_reference/interpolate.rst
doc/source/background/Background.rst
doc/source/background/Tides.rst
doc/source/index.rst
doc/source/user_guide/Examples.rst
doc/source/user_guide/Recipes.rst
doc/source/user_guide/setup-s3fs.py
doc/source/user_guide/xarray-predict.py
doc/source/user_guide/xarray.rst
doc/source/user_guide/zarr-to-s3-obstore.py
pixi.lock
pyTMD/crs.py
pyTMD/interpolate.py
pyTMD/io/constituents.py
pyTMD/io/model.py
pyTMD/predict.py
pyproject.toml
test/test_download_and_read.py
test/test_interpolate.py
test/test_perth3_read.py

docs: add s3 recipes and examples
chore: add aws feature dependencies to pixi
chore: update pixi lock file
docs: add pixi task that can create HTML documentation
feat: use vectorized linear interpolator in `infer_minor`
feat: improve performance of `bilinear` interpolation
test: add xarray tests
ci: add xarray to environment
starting work for #452

feat: add functions for converting models to `xarray`

---

doc/environment.yml
doc/source/api_reference/io/OTIS.rst
doc/source/api_reference/io/dataset.rst
doc/source/api_reference/io/io.rst
doc/source/background/Tides.rst
doc/source/user_guide/xarray-predict.py
pyTMD/crs.py
pyTMD/io/__init__.py
pyTMD/io/constituents.py
pyTMD/io/dataset.py
test/test_download_and_read.py
test/test_perth3_read.py

test: add xarray accessor checks

feat: add basic xarray accessor for tide model data
